//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class mat_materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mat_materia()
        {
            this.mxg_materiaxgrado = new HashSet<mxg_materiaxgrado>();
        }
    
        public int mat_id { get; set; }
        public string mat_nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mxg_materiaxgrado> mxg_materiaxgrado { get; set; }
    }
}
