//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class mxg_materiaxgrado
    {
        public int mxg_id { get; set; }
        public Nullable<int> mxg_id_grd { get; set; }
        public Nullable<int> mxg_id_mat { get; set; }
    
        public virtual grd_grado grd_grado { get; set; }
        public virtual mat_materia mat_materia { get; set; }
    }
}
